# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 491)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(160, 227, 227);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(203, 203, 203);\n"
"border-radius: 15px")
        self.label.setObjectName("label")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(20, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(180, 270, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(260, 270, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_6.setObjectName("btn_6")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(100, 410, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_0.setObjectName("btn_0")
        self.btn_del_elem = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del_elem.setGeometry(QtCore.QRect(260, 130, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_del_elem.setFont(font)
        self.btn_del_elem.setStyleSheet("background-color: rgb(255, 138, 70);\n"
"border-radius: 15px")
        self.btn_del_elem.setObjectName("btn_del_elem")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(100, 340, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_1.setObjectName("btn_1")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(260, 410, 71, 61))
        self.btn_equal.setMinimumSize(QtCore.QSize(71, 61))
        self.btn_equal.setMaximumSize(QtCore.QSize(71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("background-color: rgb(110, 210, 0);\n"
"border-radius: 15px")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(100, 270, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_4.setObjectName("btn_4")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(260, 340, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_3.setObjectName("btn_3")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(180, 340, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_2.setObjectName("btn_2")
        self.btn_a_in_x_root = QtWidgets.QPushButton(self.centralwidget)
        self.btn_a_in_x_root.setGeometry(QtCore.QRect(100, 130, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_a_in_x_root.setFont(font)
        self.btn_a_in_x_root.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_a_in_x_root.setObjectName("btn_a_in_x_root")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(100, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_7.setObjectName("btn_7")
        self.btn_percent = QtWidgets.QPushButton(self.centralwidget)
        self.btn_percent.setGeometry(QtCore.QRect(180, 130, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_percent.setFont(font)
        self.btn_percent.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_percent.setObjectName("btn_percent")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(180, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(260, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px\n"
"")
        self.btn_9.setObjectName("btn_9")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(20, 410, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_div.setObjectName("btn_div")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(20, 270, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_comma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comma.setGeometry(QtCore.QRect(180, 410, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_comma.setFont(font)
        self.btn_comma.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border-radius: 15px")
        self.btn_comma.setObjectName("btn_comma")
        self.btn_num_in_x_degree = QtWidgets.QPushButton(self.centralwidget)
        self.btn_num_in_x_degree.setGeometry(QtCore.QRect(20, 130, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_num_in_x_degree.setFont(font)
        self.btn_num_in_x_degree.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_num_in_x_degree.setObjectName("btn_num_in_x_degree")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(20, 340, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_mult.setFont(font)
        self.btn_mult.setStyleSheet("background-color: rgb(255, 207, 165);\n"
"border-radius: 15px")
        self.btn_mult.setObjectName("btn_mult")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()
        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_del_elem.setText(_translate("MainWindow", "⌫"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_a_in_x_root.setText(_translate("MainWindow", "√a"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_percent.setText(_translate("MainWindow", "%"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_comma.setText(_translate("MainWindow", ","))
        self.btn_num_in_x_degree.setText(_translate("MainWindow", "**"))
        self.btn_mult.setText(_translate("MainWindow", "*"))

    def add_function(self):
        self.btn_0.clicked.connect(lambda: self.write_number(self.btn_0.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))

        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_div.clicked.connect(lambda: self.write_number(self.btn_div.text()))
        self.btn_mult.clicked.connect(lambda: self.write_number(self.btn_mult.text()))
        self.btn_comma.clicked.connect(lambda: self.write_number("."))
        self.btn_percent.clicked.connect(lambda: self.write_number("/100"))
        self.btn_a_in_x_root.clicked.connect(lambda: self.write_number("**0.5"))
        self.btn_num_in_x_degree.clicked.connect(lambda: self.write_number(self.btn_num_in_x_degree.text()))
        self.btn_del_elem.clicked.connect(lambda: self.write_number(self.btn_del_elem.clicked.text()))

        self.btn_equal.clicked.connect(self.result)


    def write_number(self, number):
        if self.label.text() == "0" or self.is_equal:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text() + number)


    def result(self):
        res = eval(self.label.text())
        self.label.setText(str(res))
        self.is_equal = True





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
